# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build docker image
    pool:
      vmImage: ubuntu-latest
    steps:
   # - script: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 391122274211.dkr.ecr.us-east-1.amazonaws.com
    - script: (Get-ECRLoginCommand).Password | docker login --username AWS --password-stdin 012345678910.dkr.ecr.us-east-1.amazonaws.com
      displayName: 'Login to AWS'   
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    - task: Docker@2
      displayName: Build an image from the docker file
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
           
    - task: PublishPipelineArtifact@1
      displayName: Publish
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        publishLocation: 'pipeline'
        artifact: 'drop'   

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy to ECS cluster
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build the image in QA
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)         
