# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: MyBuild
  displayName: Build image from docker file
  jobs:
  - job: MyBuild
    displayName: Changing display name Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image ids the step
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- stage: MyQA
  displayName: MyQA
  jobs:
  - job: MyBuild
    displayName: This is QA Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build the image in QA
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)         
