# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build docker image
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: aws ecr get-login-password --no-include-email --region us-east-1
      displayName: 'Login to AWS'   
    - task: Docker@2
      displayName: Build an image from the docker file
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
           
    - task: PublishPipelineArtifact@1
      displayName: Publish
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        publishLocation: 'pipeline'
        artifact: 'drop'   

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy to ECS cluster
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build the image in QA
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)         
